### ISSUE TITLE
Cannot 'try it out' using swagger after authorize

### ISSUE THREAD

**Issue by yovierayz** [brunohbrito/JPProject.IdentityServer4.SSO#21]
I'm try to run backend and frontend project, and i got a problem like this :

![image](https://user-images.githubusercontent.com/2038089/72958313-5c106f80-3dd9-11ea-9b16-7715476cea02.png)

![image](https://user-images.githubusercontent.com/2038089/72963525-26c04d80-3dea-11ea-9d2e-0a38ee4117e8.png)

but swagger don't have authorization to access Management API or i missing configuration?
problem is free when i remove this policy :
![image](https://user-images.githubusercontent.com/2038089/72965435-e1eae580-3dee-11ea-8e41-b94439cf76e6.png)
![image](https://user-images.githubusercontent.com/2038089/72965952-3478d180-3df0-11ea-9f47-7c10b7403aae.png)

Thanks :)

**Comment by brunohbrito** [comment]
I'll check it asap

**Comment by brunohbrito** [comment]
It's working after 3.2.0

https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/pull/28
