### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by alejsouza** [brunohbrito/JPProject.IdentityServer4.SSO#25]
Seems demo's pages are not working. For example if you try to list the users... the page show please wait message for ever :)

**Comment by brunohbrito** [comment]
Hi @alejsouza,

Our SSL certificate has expired. We're working to get it back again asap.

**Comment by brunohbrito** [comment]
We are online again!

Sorry, our cron job at demo server didn't work and ssl wasn't renew.
