### ISSUE TITLE
Updating client creates duplicate children entries in Client (2.0 Branch)

### ISSUE THREAD

**Issue by dimitertodorov** [brunohbrito/JPProject.IdentityServer4.SSO#27]
This is an issue experienced on the latest 2.0 branch. master is ok.

When updating an existing client, the child relationships are duplicated.
Scopes, Grants, Redirect URIs

**To Reproduce**
1. Go to JPAdmin and take an existing client.
2. Clone the client.
3. Edit any field on the base client.
4. Save
5. Reload client view
6. Receive the following error on the JPProject.Api.Management

```
IdentityServer4.EntityFramework.Entities.Client -> IdentityServer4.Models.Client

Destination Member:
AllowedGrantTypes

 ---> System.InvalidOperationException: Grant types list contains duplicate values
```

Checking the database reveals that all children of the Client have been duplicated.

**Comment by brunohbrito** [comment]
I'll investigate

**Comment by brunohbrito** [comment]
Fixed at https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/pull/28
