### ISSUE TITLE
I can't add new migration

### ISSUE THREAD

**Issue by Matias-Cabral** [brunohbrito/JPProject.IdentityServer4.SSO#33]
I try to add a new migration with new tables, but I cannot correctly generate the migration file with add-migration.

**Comment by Matias-Cabral** [comment]
For Instance, I am trying to add a new table called Tenant, but when I try to run a migration, I get an error Your target project '' doesn't match your migrations assembly 'COACore.Sso.EntityFrameworkCore.SqlServer'.

**Comment by brunohbrito** [comment]
Hi @Matias-Cabral,

I'll explain the steps to add new migration.

1. Open `src/Frontend/Jp.UI.SSO/appsettings.json`
2. Change `ApplicationSettings:DatabaseType` to one of these options
   * SqlServer
   * MySql
   * Postgre
   * Sqlite
3. Check the connection string (In fact the only provider who checks the connection string is MySql)
4. Open terminal at folder `src/Backend/Jp.Database` and do the following command:
``` ps1
dotnet ef migrations add Initial -c SsoContext -s ../../Frontend/Jp.UI.SSO/Jp.UI.SSO.csproj
```
