### ISSUE TITLE
Can't find /Frontend/Jp.AdminUI In this Repo

### ISSUE THREAD

**Issue by yehia2amer** [brunohbrito/JPProject.IdentityServer4.SSO#34]
**Describe the bug**
In the documentation I should find a project called "/Frontend/Jp.AdminUI" but I cannot find it in this Repo !

Is there any alternatives in SSO Repo ?

**Comment by brunohbrito** [comment]
Hi @yehia2amer 

We've decided to keep them in separeted repo. Since it's possible to use admin-ui in another IdentityServer4 instances.
