### ISSUE TITLE
About CORS errors

### ISSUE THREAD

**Issue by JoaoOxOc** [brunohbrito/JPProject.IdentityServer4.SSO#37]
Hi,

I just checked that the demo of this project has CORS error.

I think you can solve them by applying the actual array of permitted URL'S:
1 - get the list of URL's from appsettings: 
`string[] corsUrl = configuration.GetSection("ApplicationSettings:Cors").Get<string[]>();`

2 - Load the array on startup: 
```
services.AddCors(options =>
            {
                options.AddPolicy("Default",
                    builder => builder.AllowAnyOrigin()
                        .WithOrigins(corsUrl)
                        .SetIsOriginAllowed((host) => true)
                        .AllowAnyMethod()
                        .AllowAnyHeader());
            });
```

**Comment by louiseJing** [comment]
@JoaoOxOc  I add the code segment to the project. But when I published in IIS,brower the Web.the CORS error already exist.
