### ISSUE TITLE
Is it possible to use active directory credentials for SSO?

### ISSUE THREAD

**Issue by arisliang** [brunohbrito/JPProject.IdentityServer4.SSO#38]
Active directory maintains user name and passwords, is it possible to integrate with that?

**Comment by brunohbrito** [comment]
Hi @arisliang,

Yes, it's totally possible. 

You need to change Login Flow at SSO/LoginController. And desconsider User Management UI, since it will won't help you.

**Comment by yehia2amer** [comment]
Hi @arisliang ,
If you mean by that using LDAP protocol for Authentication. Then you can use "Novell.Directory.Ldap" Library to Authenticate the user and then Pass LDAP Attributes as user claims in identity Server.

There is an Implementation of that in here if you want to take a look at it: https://github.com/Nordes/IdentityServer4.LdapExtension/blob/master/IdentityServer.LdapExtension/LdapService.cs

**Comment by arisliang** [comment]
thanks, will give it a try.
