### ISSUE TITLE
confirm-email: userId sent but frontend expects user 

### ISSUE THREAD

**Issue by pcbl** [brunohbrito/JPProject.IdentityServer4.SSO#44]
**Describe the bug**
Hi,

I noticed one situation which I belibe to be a Bug. Please correct me if I Am wrong:

https://github.com/brunohbrito/JPProject.Core/blob/d77db0ce2763d6cb1285308781f3f18a9c382417/src/SSO/JPProject.Sso.AspNetIdentity/Services/UserService.cs#L99

At this spot the link is generated with userId...

On the other end, at the front-end, an attribute named user is expected:
https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/blob/13660631a97a5186e1a2e69cd5b228bbc09b6fab/src/Frontend/Jp.UserManagement/src/app/pages/confirm-email/confirm-email.component.ts#L44

This leads to the situation where the user cannot confirm his mail...

**To Reproduce**
Just create a new user with Mail feature active. Once the user clicks the confirm email button, the mail never gets confirmed...

**Comment by brunohbrito** [comment]
I'm checking
