### ISSUE TITLE
Missing AdminUI project

### ISSUE THREAD

**Issue by 206mph** [brunohbrito/JPProject.IdentityServer4.SSO#53]
I cloned the project and it's running but noticed that \src\Frontend\Jp.AdminUI is missing. Looking around, I do see that both build.bat and start.bat in the build folder do reference the folder but it's not there. If the code in the JPProject.IdentityServer4.AdminUI repo up to date with the latest files? I did get it running and connected to this builds API but thought I'd mention it.

Before I forget, THANK YOU for all the work on this project! It's very much appreciated!!!

**Comment by brunohbrito** [comment]
@206mph I'll change build and start files. Thanks to report it.

I've splited the code base. Now AdminUI and SSO are separated projects. You can check AdminUI at:
https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI
