### ISSUE TITLE
CORS access in docker-compose

### ISSUE THREAD

**Issue by layinka** [brunohbrito/JPProject.IdentityServer4.SSO#57]
I tried running the full project (version 3.1) via docker-compose.

I have the instances running, but when i try to access any of the adminUI or user apps, i get errors pertaining to CORS.

`Access to XMLHttpRequest at 'http://jpproject-sso:5001/.well-known/openid-configuration' from origin 'http://jpproject-sso:4400' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I am running this on windows

**Comment by layinka** [comment]
Please, any word on this

**Comment by layinka** [comment]
Still no word on this?

**Comment by brunobritodev** [comment]
Hi @layinka 

When you run it from docker-compose, you need to change your hosts. It's a known problem to keep the same Authority across the systems.

Said that, change you http://jpproject-sso:4400 to http://localhost:4400. The only one who needs to run in this specific url is the SSO.
