### ISSUE TITLE
Login-callback redirect to 404 Error on prod with Https

### ISSUE THREAD

**Issue by avmp2208** [brunohbrito/JPProject.IdentityServer4.SSO#58]
Hello, thanks for this project it is really great,

My issue is, I was trying to use this example from zero, I just installed the code for a quick start, locally works perfectly but when I deployed the code to my hosting turns out that redirecting while login to user management or admin ui urls im having a 404 Status even if im already logged the page for example https://subdomain.domainname.com/login is 404 status but im able to see the login page only with the login button, if I click on it I get 404 to the login-callback page

**To Reproduce**
1. Go to 'https://identity.rankeadictos.cl/'
2. Login with the Bruno's default credentials.
3. Click on 'User Management UI link'
4. F12 to see the console and what the issue is.
5. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10584870/87112618-4c2b0180-c23a-11ea-9340-2a61fea93d25.png)

I havent changed anything to upload the code to webhosting, I only changed the Urls respectively 

Regards

**Comment by brunobritodev** [comment]
By the screenshot I suppose it's a IIS server, right?

I guess it's a routing problem at IIS servers. There is a [web.config](https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/blob/master/src/Frontend/Jp.UserManagement/src/web.config), which you can use to solve it.

**Comment by avmp2208** [comment]
Actually the web.config is pretty basic, the only change I added was the OutOfProcess because of the hosting does not support multiple apps for a single pool 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Jp.UI.SSO.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess" />
    </system.webServer>
  </location>
</configuration>`

So, I dont know what actually I can change here, if locally works why doesn't over the webhosting ?

Thanks for your reply.

**Comment by brunobritodev** [comment]
Because locally your UserManagement is running from node webserver. If is the docker version, then it's running from nginx.

When you publish it to run under IIS. Then you need to configure your routes. Angular Apps running under IIS is slightly different. you have to modify the default routes.

Your config above it's from https://usermanagement.rankeadictos.cl/ ? 

The web.config I've mentioned was running fine in Azure App Service for UserManagement and AdminUI.

An example of running Angular from Azure App Service:

![image](https://user-images.githubusercontent.com/7241156/87178206-2ee64980-c2b3-11ea-99ad-2243384a9e77.png)

**Comment by avmp2208** [comment]
Sorry my bad, I was looking into de wrong web.config file, I changed the rules as you mentioned, now it is working fine. 
Thank you very much Bruno, I appreciate you work.,
