### ISSUE TITLE
Can't find MFA support in code

### ISSUE THREAD

**Issue by 206mph** [brunohbrito/JPProject.IdentityServer4.SSO#64]
In the documentation, you reference MFA. How is MFA implemented? I can't seem to find anything in code to enable MFA or what forms are used. Does it support authenticator apps, a code via sms/email, or something else?

It looks like if we want to add that, I'll need to modify the JPProject.Core so the AminAPI can provide the functionality for configuration then change the SSO to implement MFA during login.

BTW, thanks for all the work you've put into this! I greatly appreciate the head start into what we're doing.

**Comment by brunobritodev** [comment]
Yes it supports. You have to change the ASP.NET Identity configuration to setup SMS or E-mail MFA
