### ISSUE TITLE
Cannot debug in VS 2019

### ISSUE THREAD

**Issue by DavidDury** [brunohbrito/JPProject.IdentityServer4.SSO#68]
Hi,

I want to run this project locally in VS2019 and check it out:

- I got latest code
- modified the connection string, using SQL Server locally, generated the migrations and updated the database.
- when I try to debug I set as start projects:

![image](https://user-images.githubusercontent.com/11799340/93894838-dc37fd80-fcf7-11ea-85d5-986909e8a915.png)

- and browser show's this: 

![image](https://user-images.githubusercontent.com/11799340/93894932-f1ad2780-fcf7-11ea-8bec-0bcbccb7509f.png)

Any idea what I do wrong?

**Comment by brunobritodev** [comment]
Maybe you'r trying to run with IIS instead Kestrel?

**Comment by DavidDury** [comment]
Can you elaborate a bit?
