### ISSUE TITLE
Unable to remove User's Claim

### ISSUE THREAD

**Issue by Messan** [brunohbrito/JPProject.IdentityServer4.SSO#7]
**Describe the bug**
Unable to remove a claim associated with a user. The API error message is __{"errors":{"RemoveUserClaimCommand":["Username must be set"]},"title":"One or more validation errors occurred.","status":400}

**To Reproduce**
1. Go to 'Users - Claims'
2. Click on 'the red cross to delete a claim'
4. See error: "1 Unknown error"

**Expected behavior**
the claim should be deleted. 
after checking the controller's action, this is normal because the "username"  is never bind to a parameter
        [HttpDelete, Route("{username}/claims/{type}"), Authorize(Policy = "Admin")]
        public async Task<ActionResult> RemoveClaim(string type, string value)
        {
            var model = new RemoveUserClaimViewModel(type, value);
            await _userManageAppService.RemoveClaim(model);
            return ResponseDelete();
        }
Also, looking at the network traffic in the browser, the claim value doesn't seem to be passed from the Angular Frontend

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Regards

**Comment by brunohbrito** [comment]
Hi, I got the problem and fixed it!

Thank you!
