### ISSUE TITLE
Problem to run "docker-run.bat"

### ISSUE THREAD

**Issue by pedropaulovtz** [brunohbrito/JPProject.IdentityServer4.SSO#76]
**Describe the bug**
I'm getting an error when i run the "docker-run.bat"

**To Reproduce**
1. Install Docker
2. Download https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/releases/download/3.0.0/jpproject-docker.zip
3. Extract
4. Make sure the Docker is running
5. Run the "docker-run.bat"
6. Press any key

**Screenshots**

![image](https://user-images.githubusercontent.com/26727145/104640612-7648fa80-5687-11eb-9fc5-3d846d82bde0.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by devops1107** [comment]
same issue

**Comment by KhalilMohammad** [comment]
I was getting the same error, my docker client was not running.

**Comment by thebestgin** [comment]
Same on Linux Mint. Many files and folders are missing to run compose.
