### ISSUE TITLE
Edge Not Working

### ISSUE THREAD

**Issue by mbasij1** [brunohbrito/JPProject.IdentityServer4.SSO#77]
when using edge and chrome for login, after submitting the login button, the login page every time shows and does not redirect to the next pages. the login is a success and the redirect to /connect.... but the login page showed again. this is ok when using firefox and worked correctly.

How To Solve:
If change HTTP to HTTPS protocols everything is ok! but you should solve bigger problems! usings HTTPS internal and outer Kubernetes network have more problems!

**Comment by louiseJing** [comment]
the https://localhost:5000/ use http ,login failed.
